"""What a method's script fixes, and what its library exposes anyway.

`params_for` reports the hyperparameters a method accepts on its command line.
For most methods that set is empty: the benchmark scripts pin their settings in
source, and this package never edits `tools_scripts/`. An empty `tunable` does
not mean the method has no hyperparameters.

This module adds the two missing facts, generated by
`tools/gen_upstream_knobs.py`, which checks every `file:line` against the
upstream scripts: what each script pins, and the knobs the wrapped library
documents but the script never surfaces.
"""
from __future__ import annotations

import functools
from pathlib import Path

_DATA = Path(__file__).parent / "upstream_knobs.yaml"


@functools.lru_cache(maxsize=1)
def _table() -> dict:
    if not _DATA.is_file():
        return {}
    import yaml
    try:
        return yaml.safe_load(_DATA.read_text()) or {}
    except Exception:  # noqa: BLE001 - a malformed table must not break discovery
        return {}


def knobs_for(method: str) -> dict:
    """Return ``{fixed_in_script, upstream_knobs, upstream_url, notes}``.

    Empty lists mean the audit has nothing recorded for this method - either it
    already exposes its hyperparameters on the command line (see `params_for`),
    or it was not part of the audited set. Absence is not a claim that the
    method fixes nothing.
    """
    entry = _table().get(method) or {}
    return {
        "fixed_in_script": list(entry.get("fixed_in_script") or []),
        "upstream_knobs": list(entry.get("upstream_knobs") or []),
        "upstream_url": entry.get("upstream_url") or None,
        "notes": entry.get("notes") or None,
    }


def audited_methods() -> list[str]:
    """Methods the upstream-knob audit covers."""
    return sorted(_table())
